apiVersion: v1
kind: Service
metadata:
  name: plateforme-service
  labels:
    app: plateforme
spec:
  type: NodePort
  selector:
    app: plateforme
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP